# Generated by Django 4.2.13 on 2024-05-15 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, help_text='Good description', max_length='500', null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(help_text='Category', max_length=50, verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Discount', max_digits=5, verbose_name='discount'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='Picture of product', null=True, upload_to='media/products', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(help_text='Name of the product', max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Price of the product', max_digits=10, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(help_text='Unique ID', max_length=50, unique=True, verbose_name='SKU'),
        ),
    ]
